call CreateWriterTransforms.bat

copy ..\Transforms\WriterPracticalAdjP.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalAdvCl.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalAdvP.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalAppdx.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalComp.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalCoord.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalExcl.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalFocus.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalIntroAndTypology.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalIP.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalN.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalNeg.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalNP.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalPP.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalPron.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalProp.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalQues.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalRelCl.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
copy ..\Transforms\WriterPracticalV.xsl "C:\Program Files\PAWS\app\resources\configuration\Transforms"
