# This workflow will build a Java project with Ant and sign the dmg
#

name: macOS Build Installer with Version and sign

env:
  NOTARIZE_PASSWORD: ${{ secrets.SIL_APPLE_NOTARIZATION_PASSWORD }}
  NOTARIZE_APPLE_ID: ${{ secrets.SIL_APPLE_NOTARIZATION_USERNAME }}
  NOTARIZE_TEAM_ID: ${{ secrets.SIL_APPLE_NOTARIZATION_USERNAME }}

on:
  push:
    tags:
      - 'v*'  # Build the app for commits that are tagged starting with 'v' e.g. v1.2.3
      # to tag a commit, use "git tag v1.2.3"
      # when you then use "git push origin v1.2.3" this workflow will be invoked
#    branches: [ "buildSignMacOS" ]

jobs:
  build-installer:

    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set VERSION (e.g. 1.0.0) and FULL_VERSION (e.g. 1.0.0-abcdef4)
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          SHORT_SHA=$(git rev-parse --short HEAD)
          FULL_VERSION="${VERSION}-${SHORT_SHA}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
        shell: bash

      - name: Validate version format
        run: |
          echo ${VERSION}
          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
            exit 1
          fi
        shell: bash

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'zulu'
          java-package: 'jdk+fx'
          architecture: 'aarch64'
      - name: Build with Ant
        run: |
          ant -noinput -buildfile build.xml
        shell: bash
      - name: Run the macOS installer script
        run: |
          cd installer/macos
          chmod +x *.sh
          ./BuildMacOS.sh ${{ env.VERSION }}
        shell: bash
      - name: Rename dmg file with version
        env:
          PUBLISH_PATH: 'installer/macos'
        run: |
          ls -l ${{env.PUBLISH_PATH}}
          mv ${{env.PUBLISH_PATH}}/PAWS-${{ env.VERSION }}.dmg PAWS-${{ env.VERSION }}.dmg

      - uses: actions/upload-artifact@v4
        with:
          name: PAWS
          path: PAWS-*.dmg
          if-no-files-found: error

  sign-installer:
    name: Sign PAWS installer
    needs: build-installer
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: PAWS

      - name: Set VERSION (e.g. 1.0.0) and FULL_VERSION (e.g. 1.0.0-abcdef4)
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          SHORT_SHA=$(git rev-parse --short HEAD)
          FULL_VERSION="${VERSION}-${SHORT_SHA}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
        shell: bash

      # If a notarization fails, uncomment the following and replace the GUID with the one from
      # notarization output
      # Get notarization log of last run
#      - name: Get notarization log
#        run: |
#          echo Before trying to get notarization log of last run
#          xcrun notarytool log 8e14c2f1-b6f8-4b1b-ae6c-450028b45767 --apple-id ${{ secrets.SIL_APPLE_NOTARIZATION_USERNAME }} --team-id "3YE4W86L3G" --password ${{ secrets.SIL_APPLE_NOTARIZATION_PASSWORD }}

      - name: Add certificate to Keychain
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.SIL_APPLE_DEVELOPER_ID_APPLICATION_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.SIL_APPLE_DEVELOPER_ID_APPLICATION_PASSWORD }}
        run: |
          # Create a temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          # Import the certificate
          curl -O ${{ secrets.SIL_APPLE_DEVELOPER_ID_APPLICATION_CERT_URL }}
          security import sil_developer_id_application_cert.p12 -k build.keychain -P ${{ secrets.SIL_APPLE_DEVELOPER_ID_APPLICATION_PASSWORD }} -T /usr/bin/codesign

          # Allow codesign to access the certificate without prompts
          #echo before allow codesign to access the certificate without prompts
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          #echo after allow codesign to access the certificate without prompts

      - name: Attach dmg
        run: |
          yes | PAGER=cat hdiutil attach PAWS-*.dmg
          echo
          echo ls
          ls /Volumes/PAWS

      - name: Create Clean Entitlements File
        run: |
          cat <<EOF > installer/macos/entitlements.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.security.cs.allow-jit</key>
              <true/>
              <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
              <true/>
              <key>com.apple.security.cs.disable-library-validation</key>
              <true/>
          </dict>
          </plist>
          EOF
        shell: bash

      - name: Sign dmg and app
        run: |
          # leaving comments used for debugging in case we need them again
          #echo start
          #pwd
          #ls -l
          mkdir dmgContents
          cp -R /Volumes/PAWS dmgContents
          cd dmgContents/PAWS
          cd PAWS.app/Contents/app/
          #pwd
          #ls -lR resources
          #jar xf paws.jar resources/Keyboards/macOS/xkbswitch org/sil/paws/resources/Keyboards/macOS/xkbswitch
          chmod a+w resources/Keyboards/macOS/xkbswitch
          #chmod a+w org/sil/paws/resources/Keyboards/macOS/xkbswitch
          echo sign xkbswitch
          #pwd
          #ls -l
          #echo four up
          #ls -l ../../../..
          codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements ../../../../../installer/macos/entitlements.plist resources/Keyboards/macOS/xkbswitch -v
          #codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements ../../../../../installer/macos/entitlements.plist org/sil/paws/resources/Keyboards/macOS/xkbswitch -v
          echo before updating xkbswitch in paws.jar; the version of jar is
          jar --version
          jar uf paws.jar resources/Keyboards/macOS/xkbswitch resources/Keyboards/macOS/xkbswitch
          echo after updating xkbswitch in paws.jar
          #rm -r org
          #cd libs/jna/
          cd libs
          echo jna
          pwd
          ls -l
          jar xf jna-5.11.0.jar com/sun/jna/darwin-aarch64/libjnidispatch.jnilib com/sun/jna/darwin-x86-64/libjnidispatch.jnilib
          echo sign jna
          codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements ../../../../../../../installer/macos/entitlements.plist com/sun/jna/darwin-aarch64/libjnidispatch.jnilib -v
          codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements ../../../../../../../installer/macos/entitlements.plist com/sun/jna/darwin-x86-64/libjnidispatch.jnilib -v
          echo update jna
          jar uf jna-5.11.0.jar com/sun/jna/darwin-aarch64/libjnidispatch.jnilib com/sun/jna/darwin-x86-64/libjnidispatch.jnilib
          rm -r com
          cd ../../../../..
          echo fx stuff
          #pwd
          #ls -l
          # -------------  sign all JavaFX runtime executables included in the app
          # without this, the notarization fails.
          # For some reason, there are two libjli.dylib files; notarization has a problem with this
          # Find all .dylib files and sign them
          # {} is a placeholder for the filename
          # + at the end is faster as it passes multiple files to one command
          find PAWS.app/Contents/runtime -name "*.dylib" -exec \
            codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" \
            --timestamp --options runtime --entitlements ../../installer/macos/entitlements.plist \
            {} +
          # following is a JDK 25 file
          codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements ../../installer/macos/entitlements.plist PAWS.app/Contents/runtime/Contents/Home/lib/jspawnhelper
          codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements ../../installer/macos/entitlements.plist PAWS.app/Contents/MacOS/PAWS -v
          # libjli.dylib is there two times; remove the non -standard one
          rm -f PAWS.app/Contents/runtime/Contents/MacOS/libjli.dylib
          # -------------  sign the main app itself
          echo sign PAWS.app
          codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements ../../installer/macos/entitlements.plist PAWS.app -v
          echo verify the app
          codesign -vvv --deep --strict PAWS.app
          cd ..
          echo recreate dmg
          #pwd
          # ln -s /Applications PAWS/Applications
          hdiutil create -volname PAWSInstaller -srcfolder PAWS -ov -format UDZO PAWS-Signed.dmg
          mv PAWS-Signed.dmg ../PAWS-Signed.dmg
          cd ..
          echo sign dmg
          #pwd
          #ls -l
          codesign --deep --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime --entitlements installer/macos/entitlements.plist PAWS-Signed.dmg -v
          #echo rename to include version number
          #mv PAWS-1.6.2.dmg PAWS-Signed.dmg
          #echo time stamp for signed dmg:
          #ls -l PAWS*.dmg

      # Verify the signature
      - name: Verify signature
        run: |
          codesign --verify --verbose PAWS-Signed.dmg
          ls -l /Applications

     # Notarize the DMG
      - name: Notarize DMG
        uses: GuillaumeFalourd/notary-tools@v1
        with:
          product_path: PAWS-Signed.dmg
          apple_id: ${{ secrets.SIL_APPLE_NOTARIZATION_USERNAME }}
          password: ${{ secrets.SIL_APPLE_NOTARIZATION_PASSWORD }}
          team_id: "3YE4W86L3G"
          # Not mandatory inputs
          staple: 'false'
          xcode_path: '/Applications/Xcode.app'

      # Staple the notarization ticket
      - name: Staple Notarization Ticket
        run: |
          #echo time stamp for stapling
          echo before stapling
          ls -l PAWS-*.dmg
          xcrun stapler staple PAWS-Signed.dmg
          echo after stapling
          ls -l PAWS-*.dmg
          echo rename to include version number
          mv PAWS-Signed.dmg PAWS-${{ env.VERSION }}.dmg

      - uses: actions/upload-artifact@v4
        with:
          name: PAWSSigned
          path: PAWS-*.dmg
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: sign-installer
    runs-on: macos-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PAWSSigned
      - name: Check dmg
        run: |
          echo Before release
          ls -l PAWS-*.dmg

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: PAWS-*.dmg
          body: |
            Release for version ${{ github.ref }}
          draft: true
